CREATE TABLE `java`.`product` (
  `PRODUCTID` VARCHAR(10) NOT NULL COMMENT '',
  `PRODUCTNAME` VARCHAR(30) NOT NULL COMMENT '',
  `QUANTITY` INT NOT NULL COMMENT '',
  `PRICE` DECIMAL(7,2) NOT NULL COMMENT '',
  `CATEGORY` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`PRODUCTID`)  COMMENT '');
